version: '3.8'

services:
  app:
    build: .
    container_name: jobportal_app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html/jobportal
    depends_on:
      - db

  db:
    image: mariadb:10.6
    container_name: jobportal_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: jobportal
      MYSQL_USER: jobuser
      MYSQL_PASSWORD: jobpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/database_jobportal.sql:/docker-entrypoint-initdb.d/database_jobportal.sql

volumes:
  db_data: